services:
  backend:
    restart: always
  frontend:
    restart: always
  nginx:
    restart: always
  smtp-server:
    restart: always
  imap-server:
    restart: always
  celery-worker:
    restart: always
  celery-beat:
    restart: always
  postgres:
    restart: always
  redis:
    restart: always
  spamassassin:
    restart: always
  clamav:
    restart: always
  fail2ban:
    restart: always
